package main

import (
	"context"
	"fmt"
	"net/http"

	greetv1 "github.com/horirinn2000/grpc-connect-envoy/proto/gen/greet/v1"        // generated by protoc-gen-go
	"github.com/horirinn2000/grpc-connect-envoy/proto/gen/greet/v1/greetv1connect" // generated by protoc-gen-connect-go
)

type GreetServer struct{}

func (s *GreetServer) Greet(
	ctx context.Context,
	req *greetv1.GreetRequest,
) (*greetv1.GreetResponse, error) {
	res := &greetv1.GreetResponse{
		Greeting: fmt.Sprintf("Hello, %s!", req.Name),
	}
	return res, nil
}

func main() {
	greeter := &GreetServer{}
	mux := http.NewServeMux()
	path, handler := greetv1connect.NewGreetServiceHandler(greeter)
	mux.Handle(path, handler)
	s := http.Server{
		Addr:      "0.0.0.0:9090",
		Handler:   mux,
	}
	s.ListenAndServe()
}
